name: client_food
description: food client for hackathon.
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  adaptive_navigation: ^0.0.9
  auto_route: ^7.8.3
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0
  intl: ^0.18.0
  responsive_grid_list: ^1.4.0

dev_dependencies:
  auto_route_generator: any
  bloc_test: ^9.1.4
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

flutter_gen:
  integrations:
    flutter_svg: true